In [2]:
import numpy as np
import pandas as pd

In [3]:
students = np.array([[1,135,34,4],
[2,160,43,5],
[3,163,40,4.3],
[4,147,44,5],
[5,138,41,4.7],
[6,149,54,3.9],
[7,136,39,4.2],
[8,154,48,4.9],
[9,137,35,3.7],
[10,165,60,4.6]])
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [4]:
median = np.median(students[:,-1])
median

4.449999999999999

In [6]:
np.median(students[:,-2])

42.0

In [8]:
np.mean(students[:,-2]) - np.median(students[:,-2])

1.7999999999999972

In [9]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [10]:
np.corrcoef(students[:,1], students[:,2])

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [11]:
np.corrcoef(students[:,1], students[:,-1])

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [12]:
np.corrcoef(students[:,2], students[:,-1])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [13]:
std = np.std(students[:,1])
std

11.083320801997928

In [14]:
np.std(students[:,-1])

0.4517742799230607

In [19]:
np.std(students[:,2])**2

60.36

In [17]:
students[:,2]

array([34., 43., 40., 44., 41., 54., 39., 48., 35., 60.])

In [20]:
np.array([x/x for x in range(1,10)]*5)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.empty((5, 1))

array([[7.74860419e-304],
       [7.74860419e-304],
       [7.74860419e-304],
       [7.74860419e-304],
       [7.74860419e-304]])

In [22]:
np.full((10, 5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.ones((5,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
np.random.randint(1, 10, (10, 10))

array([[1, 7, 1, 2, 5, 1, 2, 5, 5, 5],
       [7, 9, 4, 5, 1, 8, 2, 6, 1, 8],
       [3, 3, 8, 1, 6, 6, 9, 1, 7, 5],
       [8, 5, 3, 3, 2, 6, 7, 4, 3, 8],
       [7, 8, 4, 3, 9, 8, 2, 7, 6, 6],
       [5, 7, 7, 3, 5, 4, 6, 1, 5, 9],
       [9, 3, 6, 8, 5, 7, 7, 3, 9, 5],
       [9, 2, 6, 9, 2, 6, 7, 7, 6, 3],
       [6, 2, 6, 6, 7, 1, 1, 6, 5, 9],
       [9, 2, 9, 5, 1, 8, 3, 7, 2, 6]])

In [34]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [40]:
my_sin = np.sin(my_array)
my_sin.sum()

-0.05812430261413373

In [41]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
# my_array[1:4,1:4]=1
# my_array

In [43]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [45]:
my_sin[1:4,1:4]=1
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [46]:
my_sin.sum()

7.571718421269144

In [48]:
my_sin[:,0:4]

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ,  1.        ,  1.        ],
       [-0.99999021,  1.        ,  1.        ,  1.        ],
       [-0.28790332,  1.        ,  1.        ,  1.        ],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [57]:
my_sin_rs = np.reshape(my_sin[:,0:4], (10,2))
my_sin_rs

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

In [59]:
my_sin_rs[:,0].sum()

2.4057172058139544

In [62]:
bigdata = np.array([x**2 for x in range(100, 1001) if x % 2 == 1])
# bigdata

In [63]:
np.median(bigdata)

302501.0

In [64]:
np.std(bigdata)

292095.0301991155

In [68]:
# np.split(bigdata, [3, 5, 6, 10])
ar_0 = np.array([bigdata[x] for x in range(0, len(bigdata)) if x % 2 == 0])
ar_1 = np.array([bigdata[x] for x in range(0, len(bigdata)) if x % 2 == 1])

In [69]:
np.corrcoef(ar_0, ar_1)

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])