In [1]:
import numpy as np
import pandas as pd

In [2]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.full((5,5),1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.random.randint(0,5,3)

array([1, 3, 2])

In [12]:
np.ones((4,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((4,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [16]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [17]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_array[5]

5

In [19]:
my_array[-1]

9

In [20]:
my_array[3:6]

array([3, 4, 5])

In [21]:
my_array[1:8:3]

array([1, 4, 7])

In [26]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [23]:
my_array[1][2]

12

In [24]:
my_array[1,2]

12

In [25]:
my_array[1]

array([10, 11, 12, 13])

In [27]:
my_array[:,2]

array([ 3, 12, 47])

In [28]:
my_array[1:,1:3]

array([[11, 12],
       [46, 47]])

In [51]:
my_array[:,-3:]

array([[ 2,  3,  4],
       [11, 12, 13],
       [46, 47, 48]])

In [39]:
my_array[:,:3]

array([[ 1,  2,  3],
       [10, 11, 12],
       [45, 46, 47]])

In [37]:
my_array[:,-1].sum()

65

In [30]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [38]:
big_secret[:,-1].sum()

3154.332495807108

In [41]:
np.trace(big_secret[:,:5])

121.37188663699624

In [55]:
big_secret[:,-5:].diagonal().prod()

341505315559.2347

In [56]:
big_secret.shape

(5, 51)

In [64]:
for l in range(0, big_secret.shape[0], 2 ):
    for c in range(0, big_secret.shape[1], 2 ):
        big_secret[l,c]=-1
        
for l in range(1, big_secret.shape[0], 2 ):
    for c in range(1, big_secret.shape[1], 2 ):
        big_secret[l,c]=1   
# big_secret        

In [65]:
np.trace(big_secret[:,:5])

-1.0

In [66]:
big_secret[:,-5:].diagonal().prod()

-1.0