In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [3]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [4]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[2, 4, 7, 2, 7],
       [9, 4, 3, 1, 2],
       [0, 9, 4, 7, 8],
       [2, 8, 9, 9, 6]])

In [5]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [8]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
great_secret.shape

(100, 3)

In [18]:
np.cos(great_secret[0,]).sum()

0.16006721889793019

In [12]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [20]:
great_secret[great_secret>50].sum()

5470.0

In [21]:
great_secret.flatten()[150]

7.0710678118654755

In [23]:
np.sort(great_secret, axis=0)[-1:].sum()

115.12148016521353